### PR TITLE
Install updates

### PR DESCRIPTION
**Pull request by mrdrogdrog**
Hello,

We use this lib at https://github.com/hedgedoc/react-client and can't update @hpcc-js/wasm because of this package. 
Therefore I've created this PR.

This PR does two things:
- Update @hpcc-js/wasm to 1.15.4
- Renews the lock file to update dependencies

Please merge it and publish a new release :)

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
Huh. That's weird. On my machine the tests are running fine 🤔 I'll investigate that.

**Comment by magjac** [comment]
Just try re-running it. I've seen this kind of flakiness before.

**Review by magjac — COMMENTED** [review]
Thank you so much for this. If you could put the corresponding Graphviz version in the commit message it would great. See e.g. 8eeb63d62b81427b47fed1ff39752c50a621c3c4

**Comment by mrdrogdrog** [comment]
I update the commit

**Comment by mrdrogdrog** [comment]
The tests aren't running with Node 12. If you're okay with it then I would remove node 12 from the CI config. Its end of life was 4 months ago. https://endoflife.date/nodejs

**Comment by magjac** [comment]
I think the tests needs to be updated with respect to https://gitlab.com/graphviz/graphviz/-/merge_requests/2472.

**Comment by magjac** [comment]
@mrdrogdrog While working on porting d3-graphviz to D3 v7 I got hit by the failing tests due to https://gitlab.com/graphviz/graphviz/-/merge_requests/2472 so I updated the test data and pushed three commits to https://github.com/magjac/d3-graphviz/tree/update in case you want to rebase or cherry-pick them.

**Comment by mrdrogdrog** [comment]
Okay.. Added everything. Try it again.

**Comment by mrdrogdrog** [comment]
Seems like everything is okay now

**Comment by magjac** [comment]
I fixed one of my own spelling mistakes and merged. Thank you so much for doing this :slightly_smiling_face:

**Comment by mrdrogdrog** [comment]
Thank you for creating and maintaining this lib! ☺️

**Pull request merged**
