### PR TITLE
Upgrade to d3 version 7 and adopt type=module

### PR DESCRIPTION
**Pull request by magjac**

### CODE REVIEW

**Comment by mcmartins** [comment]
@magjac are you planning to merge and release this soon(ish)?

Thanks!

**Comment by magjac** [comment]
Yes, but I have a few test cases that do not pass yet which I need to figure out how to fix first. Hopefully I can carve out some time for this during this week.

**Comment by magjac** [comment]
Right now I'm on a detour in the https://github.com/magjac/d3-graphviz/tree/DEBUG-upgrade-to-d3-version-7 branch.

**Comment by mcmartins** [comment]
Awesome @magjac !

**Pull request merged**
